### ISSUE TITLE
你好 ，我这边下载您的代码后编译报这个错误，该如何解决

### ISSUE THREAD

**Issue by leigetiwen** [touchmii/OpenTCS-4#10]
> Task :openTCS-API-Base:compileJava
> Task :openTCS-API-Base:processResources NO-SOURCE
> Task :openTCS-API-Base:classes
> Task :openTCS-API-Base:jar
> Task :openTCS-API-Injection:compileJava
> Task :openTCS-API-Injection:processResources NO-SOURCE
> Task :openTCS-API-Injection:classes
> Task :openTCS-API-Injection:jar

> Task :openTCS-Common:compileJava FAILED
/home/jetson/tcs_workspace/OpenTCS-4-master/openTCS-Common/src/main/java/org/opentcs/util/persistence/BasePlantModelTO.java:12: error: package javax.xml.bind.annotation does not exist
import javax.xml.bind.annotation.XmlAccessType;
                                ^
/home/jetson/tcs_workspace/OpenTCS-4-master/openTCS-Common/src/main/java/org/opentcs/util/persistence/BasePlantModelTO.java:13: error: package javax.xml.bind.annotation does not exist
import javax.xml.bind.annotation.XmlAccessorType;
                                ^
/home/jetson/tcs_workspace/OpenTCS-4-master/openTCS-Common/src/main/java/org/opentcs/util/persistence/BasePlantModelTO.java:14: error: package javax.xml.bind.annotation does not exist
import javax.xml.bind.annotation.XmlAttribute;
                                ^
/home/jetson/tcs_workspace/OpenTCS-4-master/openTCS-Common/src/main/java/org/opentcs/util/persistence/BasePlantModelTO.java:15: error: package javax.xml.bind.annotation does not exist
import javax.xml.bind.annotation.XmlTransient;
                                ^
/home/jetson/tcs_workspace/OpenTCS-4-master/openTCS-Common/src/main/java/org/opentcs/util/persistence/BasePlantModelTO.java:22: error: cannot find symbol
@XmlTransient
 ^
  symbol: class XmlTransient
/home/jetson/tcs_workspace/OpenTCS-4-master/openTCS-Common/src/main/java/org/opentcs/util/persistence/BasePlantModelTO.java:23: error: cannot find symbol
@XmlAccessorType(XmlAccessType.PROPERTY)
 ^
  symbol: class XmlAccessorType
/home/jetson/tcs_workspace/OpenTCS-4-master/openTCS-Common/src/main/java/org/opentcs/util/persistence/v002/LocationTypeTO.java:14: error: package javax.xml.bind.annotation does not exist
import javax.xml.bind.annotation.XmlAccessType;
                                ^
/home/jetson/tcs_workspace/OpenTCS-4-master/openTCS-Common/src/main/java/org/opentcs/util/persistence/v002/LocationTypeTO.java:15: error: package javax.xml.bind.annotation does not exist
import javax.xml.bind.annotation.XmlAccessorType;
                                ^
/home/jetson/tcs_workspace/OpenTCS-4-master/openTCS-Common/src/main/java/org/opentcs/util/persistence/v002/LocationTypeTO.java:16: error: package javax.xml.bind.annotation does not exist
import javax.xml.bind.annotation.XmlAttribute;
                                ^
/home/jetson/tcs_workspace/OpenTCS-4-master/openTCS-Common/src/main/java/org/opentcs/util/persistence/v002/LocationTypeTO.java:17: error: package javax.xml.bind.annotation does not exist
import javax.xml.bind.annotation.XmlElement;
                                ^
/home/jetson/tcs_workspace/OpenTCS-4-master/openTCS-Common/src/main/java/org/opentcs/util/persistence/v002/LocationTypeTO.java:18: error: package javax.xml.bind.annotation does not exist
import javax.xml.bind.annotation.XmlType;
                                ^
/home/jetson/tcs_workspace/OpenTCS-4-master/openTCS-Common/src/main/java/org/opentcs/util/persistence/v002/PlantModelElementTO.java:14: error: package javax.xml.bind.annotation does not exist
import javax.xml.bind.annotation.XmlAccessType;
                                ^
/home/jetson/tcs_workspace/OpenTCS-4-master/openTCS-Common/src/main/java/org/opentcs/util/persistence/v002/PlantModelElementTO.java:15: error: package javax.xml.bind.annotation does not exist
import javax.xml.bind.annotation.XmlAccessorType;
                                ^
/home/jetson/tcs_workspace/OpenTCS-4-master/openTCS-Common/src/main/java/org/opentcs/util/persistence/v002/PlantModelElementTO.java:16: error: package javax.xml.bind.annotation does not exist
import javax.xml.bind.annotation.XmlAttribute;
                                ^
/home/jetson/tcs_workspace/OpenTCS-4-master/openTCS-Common/src/main/java/org/opentcs/util/persistence/v002/PlantModelElementTO.java:17: error: package javax.xml.bind.annotation does not exist
import javax.xml.bind.annotation.XmlElement;
                                ^
/home/jetson/tcs_workspace/OpenTCS-4-master/openTCS-Common/src/main/java/org/opentcs/util/persistence/v002/PlantModelElementTO.java:18: error: package javax.xml.bind.annotation does not exist
import javax.xml.bind.annotation.XmlSchemaType;
                                ^
/home/jetson/tcs_workspace/OpenTCS-4-master/openTCS-Common/src/main/java/org/opentcs/util/persistence/v002/PlantModelElementTO.java:19: error: package javax.xml.bind.annotation does not exist
import javax.xml.bind.annotation.XmlTransient;
                                ^
/home/jetson/tcs_workspace/OpenTCS-4-master/openTCS-Common/src/main/java/org/opentcs/util/persistence/v002/PlantModelElementTO.java:25: error: cannot find symbol
@XmlTransient
 ^
  symbol: class XmlTransient
/home/jetson/tcs_workspace/OpenTCS-4-master/openTCS-Common/src/main/java/org/opentcs/util/persistence/v002/PlantModelElementTO.java:26: error: cannot find symbol
@XmlAccessorType(XmlAccessType.PROPERTY)
 ^
  symbol: class XmlAccessorType
/home/jetson/tcs_workspace/OpenTCS-4-master/openTCS-Common/src/main/java/org/opentcs/util/persistence/v002/LocationTypeTO.java:24: error: cannot find symbol
@XmlAccessorType(XmlAccessType.PROPERTY)
 ^
  symbol: class XmlAccessorType
/home/jetson/tcs_workspace/OpenTCS-4-master/openTCS-Common/src/main/java/org/opentcs/util/persistence/v002/LocationTypeTO.java:25: error: cannot find symbol
@XmlType(propOrder = {"name", "id", "locationNamePrefix", "allowedOperations", "properties"})
 ^
  symbol: class XmlType
/home/jetson/tcs_workspace/OpenTCS-4-master/openTCS-Common/src/main/java/org/opentcs/util/persistence/v002/AllowedOperationTO.java:10: error: package javax.xml.bind.annotation does not exist
import javax.xml.bind.annotation.XmlAccessType;
                                ^
/home/jetson/tcs_workspace/OpenTCS-4-master/openTCS-Common/src/main/java/org/opentcs/util/persistence/v002/AllowedOperationTO.java:11: error: package javax.xml.bind.annotation does not exist
import javax.xml.bind.annotation.XmlAccessorType;
                                ^
/home/jetson/tcs_workspace/OpenTCS-4-master/openTCS-Common/src/main/java/org/opentcs/util/persistence/v002/AllowedOperationTO.java:17: error: cannot find symbol
@XmlAccessorType(XmlAccessType.PROPERTY)
 ^
  symbol: class XmlAccessorType
/home/jetson/tcs_workspace/OpenTCS-4-master/openTCS-Common/src/main/java/org/opentcs/util/persistence/v002/PropertyTO.java:12: error: package javax.xml.bind.annotation does not exist
import javax.xml.bind.annotation.XmlAccessType;
                                ^
/home/jetson/tcs_workspace/OpenTCS-4-master/openTCS-Common/src/main/java/org/opentcs/util/persistence/v002/PropertyTO.java:13: error: package javax.xml.bind.annotation does not exist
import javax.xml.bind.annotation.XmlAccessorType;
                                ^
/home/jetson/tcs_workspace/OpenTCS-4-master/openTCS-Common/src/main/java/org/opentcs/util/persistence/v002/PropertyTO.java:14: error: package javax.xml.bind.annotation does not exist
import javax.xml.bind.annotation.XmlAttribute;
                                ^
/home/jetson/tcs_workspace/OpenTCS-4-master/openTCS-Common/src/main/java/org/opentcs/util/persistence/v002/PropertyTO.java:15: error: package javax.xml.bind.annotation does not exist
import javax.xml.bind.annotation.XmlType;
                                ^
/home/jetson/tcs_workspace/OpenTCS-4-master/openTCS-Common/src/main/java/org/opentcs/util/persistence/v002/PropertyTO.java:21: error: cannot find symbol
@XmlAccessorType(XmlAccessType.PROPERTY)
 ^
  symbol: class XmlAccessorType
/home/jetson/tcs_workspace/OpenTCS-4-master/openTCS-Common/src/main/java/org/opentcs/util/persistence/v002/PropertyTO.java:22: error: cannot find symbol
@XmlType(propOrder = {"name", "value"})
 ^

**Comment by touchmii** [comment]
你更新一下代码, 使用./gradlew build -x test 来编译.
